title: Simmer
description: A pure Javascript reverse CSS selector engine which calculates a DOM element's unique CSS selector on the current page.
google_analytics: UA-47874971-1
show_downloads: true
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
